# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'

# whitespace
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

# git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'

# cuurent word
[[plugins]]
repo = 'dominikduda/vim_current_word'

# fzf
[[plugins]]
repo = 'junegunn/fzf.vim'

# brakets
[[plugins]]
repo = 'cohama/lexima.vim'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'
